-- Check if payslip_history table exists and its structure
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_name = 'payslip_history' 
ORDER BY ordinal_position;

-- If table doesn't exist or has wrong structure, create/drop it
DROP TABLE IF EXISTS payslip_history;

-- Create payslip_history table with correct structure
CREATE TABLE payslip_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id VARCHAR(50) NOT NULL,
    worker_type VARCHAR(20) NOT NULL CHECK (worker_type IN ('local', 'foreign')),
    payslip_month DATE NOT NULL,
    payslip_year INTEGER NOT NULL,
    basic_pay DECIMAL(10,2) DEFAULT 0,
    ot_pay DECIMAL(10,2) DEFAULT 0,
    sun_ph_pay DECIMAL(10,2) DEFAULT 0,
    monthly_allowance DECIMAL(10,2) DEFAULT 0,
    incentive_allowance DECIMAL(10,2) DEFAULT 0,
    bonus DECIMAL(10,2) DEFAULT 0,
    custom_additions JSONB DEFAULT '[]',
    total_additions DECIMAL(10,2) DEFAULT 0,
    cpf_employee_deduction DECIMAL(10,2) DEFAULT 0,
    sinda_deduction DECIMAL(10,2) DEFAULT 0,
    cpf_employer_contribution DECIMAL(10,2) DEFAULT 0,
    sdl_contribution DECIMAL(10,2) DEFAULT 0,
    total_deductions DECIMAL(10,2) DEFAULT 0,
    net_pay DECIMAL(10,2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX idx_payslip_history_worker_id ON payslip_history(worker_id);
CREATE INDEX idx_payslip_history_month ON payslip_history(payslip_month);
CREATE INDEX idx_payslip_history_year ON payslip_history(payslip_year);

-- Enable RLS (Row Level Security)
ALTER TABLE payslip_history ENABLE ROW LEVEL SECURITY;

-- Create RLS policy to allow authenticated users to read/write payslip data
CREATE POLICY "Allow authenticated users to manage payslip history" 
ON payslip_history 
FOR ALL 
USING (auth.role() = 'authenticated') 
WITH CHECK (auth.role() = 'authenticated');

-- Add updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_payslip_history_updated_at 
    BEFORE UPDATE ON payslip_history 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
